urls:
    cctray: "http://y-ci-master.dnspam/"

projects:
    - Merchandise_Service
    - Demand_Pricing_Service
    - Demand_Coefficient_Calculator
    - Pricing_App
    - Pricing_App_Stub_Verifier
    - Pricing_App_Functional_Test
    - Pricing_App_End_to_End
    - Pricing_Service_Stub_Verifier
    - Price_Config_Service
    - Merchandise_App
    - Merchandise_App_Functional_Test
    - Merchandise_App_Stub_Verifier
    - Analytics
    - Merchandise_Service_Stub_Verifier
    - Cost_Service
    - Product_Positioning_Service
    - Pricing_Tool_Service
    - Pricing_Tool_App
    - Pricing_Tool_Functional_Test
    - Chef_Repo
    - Deploy_QA
    - Deploy_Showcase
    - Last_Mile_Cukes
    - Generate_Pipeline_Properties
